-- Create contacts table for contact form submissions
-- Run this in your Supabase SQL editor

create table if not exists contacts (
  id bigint generated by default as identity primary key,
  name text not null,
  email text not null,
  message text not null,
  timestamp timestamp with time zone default timezone('utc'::text, now()) not null,
  date text,
  time text,
  created_at timestamp with time zone default timezone('utc'::text, now()) not null
);

-- Enable RLS (Row Level Security)
alter table contacts enable row level security;

-- Create policy to allow anyone to insert contacts (for contact form)
create policy "Anyone can submit contact forms"
  on contacts for insert
  with check ( true );

-- Create policy to allow service role to read contacts
create policy "Service role can read contacts"
  on contacts for select
  using ( auth.role() = 'service_role' );